version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: final-jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: artgallery_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./ArtGalleryFinal
    container_name: tomcat-backend
    ports:
      - "9091:8081"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/artgallery_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  jenkins_home:
  mysql-data:
